"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
DATA_DIR = PROJECT_ROOT / "data"
DEFAULT_WORKBOOK_PATH = DATA_DIR / "telangana_districts.xlsx"
EDUCATION_DATA_DIR = DATA_DIR / "education"
EDUCATION_LITERACY_CSV_PATH = EDUCATION_DATA_DIR / "literacy_literacy_rate.csv"
EDUCATION_SCHOOLS_CSV_PATH = EDUCATION_DATA_DIR / "schools_colleges_enrollment_seats 2016-17.csv"
EDUCATION_DROPOUT_CSV_PATH = EDUCATION_DATA_DIR / "telangana_dropout_data_2021_22.csv"
# Every source used by the education dashboard is bundled under data/education.
# Paths are intentionally project-relative so a clone works on any machine.
EDUCATION_MULTI_YEAR_FILES = {
    "2016-17": {"schools": [EDUCATION_DATA_DIR / "schools_colleges_enrollment_seats 2016-17.csv"]},
    "2017-18": {"schools": [EDUCATION_DATA_DIR / "Telangana_Schools_2017-18.csv"]},
    "2018-19": {
        "schools": [EDUCATION_DATA_DIR / "Telangana_Schools_2018-19.csv"],
        "colleges": [EDUCATION_DATA_DIR / "Telangana_College_Data_2018-19_CORRECTED.csv"],
    },
    "2019-20": {"schools": [EDUCATION_DATA_DIR / "Telangana_Schools_2019-20.csv"]},
    "2020-21": {"colleges": [EDUCATION_DATA_DIR / "Telangana_College_Data_2020-21.csv"]},
    "2021-22": {"schools": [EDUCATION_DATA_DIR / "Telangana_Schools_2021-22.csv"]},
}
EV_CHARGING_STATIONS_CSV_PATH = DATA_DIR / "ev" / "EV_Charging_stations_details_April_2024.csv"
DISTRICT_GEOJSON_PATH = PROJECT_ROOT / "frontend" / "public" / "data" / "telangana-districts.geojson"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-auqhq4kd50$1yacad4u4-io(ewf&82bp9o&esk5rpge)31!8d$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'demographics.apps.DemographicsConfig',
    'education.apps.EducationConfig',
    'ev.apps.EvConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # Override only for isolated tests; the default remains the project DB.
        'NAME': Path(os.environ.get('TELANGANA_SQLITE_PATH', BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
