# Generated by Django 6.0.7 on 2026-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('male_literate', models.PositiveIntegerField(default=0)),
                ('female_literate', models.PositiveIntegerField(default=0)),
                ('male_literacy_rate', models.FloatField(default=0)),
                ('female_literacy_rate', models.FloatField(default=0)),
                ('literacy_rate', models.FloatField(default=0)),
                ('primary_schools', models.PositiveIntegerField(default=0)),
                ('primary_enrollment', models.PositiveIntegerField(default=0)),
                ('upper_primary_schools', models.PositiveIntegerField(default=0)),
                ('upper_primary_enrollment', models.PositiveIntegerField(default=0)),
                ('high_schools', models.PositiveIntegerField(default=0)),
                ('high_enrollment', models.PositiveIntegerField(default=0)),
                ('model_schools', models.PositiveIntegerField(default=0)),
                ('model_enrollment', models.PositiveIntegerField(default=0)),
                ('kgbv_schools', models.PositiveIntegerField(default=0)),
                ('kgbv_enrollment', models.PositiveIntegerField(default=0)),
                ('central_schools', models.PositiveIntegerField(default=0)),
                ('central_enrollment', models.PositiveIntegerField(default=0)),
                ('junior_colleges', models.PositiveIntegerField(default=0)),
                ('degree_colleges', models.PositiveIntegerField(default=0)),
                ('degree_college_seats', models.PositiveIntegerField(default=0)),
                ('engineering_colleges', models.PositiveIntegerField(default=0)),
                ('engineering_college_seats', models.PositiveIntegerField(default=0)),
                ('pharmacy_colleges', models.PositiveIntegerField(default=0)),
                ('pharmacy_college_seats', models.PositiveIntegerField(default=0)),
                ('mba_colleges', models.PositiveIntegerField(default=0)),
                ('mba_college_seats', models.PositiveIntegerField(default=0)),
                ('mca_colleges', models.PositiveIntegerField(default=0)),
                ('mca_college_seats', models.PositiveIntegerField(default=0)),
                ('bed_colleges', models.PositiveIntegerField(default=0)),
                ('bed_college_seats', models.PositiveIntegerField(default=0)),
                ('law_colleges', models.PositiveIntegerField(default=0)),
                ('law_college_seats', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
