# Generated by Codex on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("education", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="EducationDropout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("primary_enrollment", models.PositiveIntegerField(default=0)),
                ("upper_primary_enrollment", models.PositiveIntegerField(default=0)),
                ("high_school_enrollment", models.PositiveIntegerField(default=0)),
                ("primary_dropout_rate", models.FloatField(default=0)),
                ("upper_primary_dropout_rate", models.FloatField(default=0)),
                ("high_school_dropout_rate", models.FloatField(default=0)),
                ("estimated_primary_dropouts", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_upper_primary_dropouts", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_high_school_dropouts", models.PositiveIntegerField(blank=True, null=True)),
                ("data_year", models.CharField(max_length=20)),
                ("data_source", models.CharField(max_length=255)),
                ("count_note", models.TextField(blank=True)),
            ],
            options={"ordering": ("name",)},
        ),
    ]
