import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { getCurrentUser, register, signIn, startGoogleSignIn } from '../services/auth'
import '../auth.css'

const messageFrom = (error) => error?.email ? (Array.isArray(error.email) ? error.email[0] : error.email) : error?.password ? (Array.isArray(error.password) ? error.password[0] : error.password) : error?.detail || error?.message || 'Something went wrong. Please try again.'

export default function Auth({ onAuthenticated }) {
  const [mode, setMode] = useState('login'), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [params] = useSearchParams(); const navigate = useNavigate(); const googleError = params.get('error')
  const submit = async (event) => { event.preventDefault(); setError(''); setBusy(true); try { const result = await (mode === 'login' ? signIn(email, password) : register(email, password)); if (!result?.user) throw { detail: 'The server did not confirm your sign-in. Please try again.' }; const user = await getCurrentUser(); if (!user) throw { detail: 'Your sign-in was not saved. Please try again.' }; onAuthenticated?.(user); navigate('/', { replace: true }) } catch (response) { setError(messageFrom(response)) } finally { setBusy(false) } }
  const google = async () => { setError(''); setBusy(true); try { window.location.assign(await startGoogleSignIn()) } catch (response) { setError(messageFrom(response)); setBusy(false) } }
  return <main className="auth-page"><section className="auth-intro"><Link to="/" className="landing-brand"><span>TS</span><div><b>Telangana</b><small>State Analytics Portal</small></div></Link><div><p className="eyebrow">Secure portal access</p><h1>Insights for a<br/><em>stronger</em> Telangana.</h1><p>Sign in to continue to the State Analytics Portal and explore trusted public data with clarity.</p></div><small className="auth-note">Government data · secure access · clear insight</small></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">Welcome</p><h2>{mode === 'login' ? 'Sign in to your account' : 'Create your account'}</h2><p className="auth-subtitle">{mode === 'login' ? 'Use your registered email and password.' : 'Register with your email to get started.'}</p>{(error || googleError) && <div className="auth-error" role="alert">{error || (googleError === 'google_cancelled' ? 'Google sign-in was cancelled. Please try again.' : 'Google sign-in could not be completed. Please try again.')}</div>}<button className="google-button" type="button" onClick={google} disabled={busy}><span>G</span>Continue with Google</button><div className="auth-divider"><span>or</span></div><form onSubmit={submit} noValidate><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com" required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder={mode === 'login' ? 'Enter your password' : 'Create a secure password'} required minLength="8" /></label>{mode === 'register' && <p className="password-hint">Use at least 8 characters and avoid a common password.</p>}<button className="auth-submit" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button></form><p className="auth-switch">{mode === 'login' ? 'New to the portal?' : 'Already have an account?'} <button type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError('') }}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div></section></main>
}
