import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, Treemap, XAxis, YAxis } from 'recharts'
import { useNavigate } from 'react-router-dom'
import { getEducationOverview } from '../api'
import DistrictCombobox from '../components/DistrictCombobox'
import '../education-dashboard.css'

const categories = ['Engineering', 'Degree', 'MBA', 'MCA', 'Pharmacy', 'Law', 'B.Ed.']
const colours = ['#6c3cf0', '#f59e0b', '#ec4899', '#4e9ce6', '#4ba879', '#c18c4e', '#9d5ce6']
const format = value => new Intl.NumberFormat('en-IN').format(value || 0)
const tooltipStyle = { borderRadius: 12, border: '1px solid #eee2d6', boxShadow: '0 10px 24px #41206e1f' }

function TreeTile({ x, y, width, height, index, name, value }) {
  return <g><rect x={x} y={y} width={width} height={height} rx={5} fill={colours[index % colours.length]} stroke="#fff" strokeWidth={2}/>{width > 68 && height > 33 && <text x={x + 8} y={y + 18} fill="#fff" fontSize={11} fontWeight="700">{name}</text>}{width > 68 && height > 50 && <text x={x + 8} y={y + 34} fill="#fff" fontSize={10}>{format(value)}</text>}</g>
}

export default function CollegeAnalytics() {
  const [overview, setOverview] = useState(null), [error, setError] = useState(''), [districtSlug, setDistrictSlug] = useState(''), [sortBy, setSortBy] = useState('total_colleges'), [institution, setInstitution] = useState('All')
  const navigate = useNavigate()
  useEffect(() => { getEducationOverview().then(setOverview).catch(e => setError(e.message)) }, [])
  const districts = overview?.districts || []
  const visible = districtSlug ? districts.filter(district => district.slug === districtSlug) : districts
  const totals = useMemo(() => Object.fromEntries(categories.map(category => [category, visible.reduce((sum, district) => sum + (district.college_distribution[category] || 0), 0)])), [visible])
  const seatTotals = useMemo(() => Object.fromEntries(categories.map(category => [category, visible.reduce((sum, district) => sum + (district.college_seat_distribution[category] || 0), 0)])), [visible])
  const selectedValue = district => institution === 'All' ? district.total_colleges : district.college_distribution[institution]
  const sorted = [...visible].sort((a, b) => { const aValue = sortBy === 'total_colleges' ? a.total_colleges : sortBy === 'total_college_seats' ? a.total_college_seats : a.college_distribution[sortBy]; const bValue = sortBy === 'total_colleges' ? b.total_colleges : sortBy === 'total_college_seats' ? b.total_college_seats : b.college_distribution[sortBy]; return bValue - aValue })
  const ranking = [...visible].sort((a, b) => selectedValue(b) - selectedValue(a)).slice(0, 10).reverse().map(district => ({ name: district.name, slug: district.slug, value: selectedValue(district) }))
  const stacked = sorted.slice(0, 10).map(district => ({ name: district.name, slug: district.slug, ...district.college_distribution }))
  if (!overview && !error) return <div className="loading">Loading college analytics…</div>
  if (error) return <div className="notice">{error}</div>
  return <div className="college-analytics">
    <section className="college-heading"><div><p className="eyebrow">Education analytics · higher education</p><h1>College analytics explorer</h1><p>District-level institution capacity and available seats across Telangana’s higher-education network.</p></div><div className="college-total"><span>Reported institutions</span><strong>{format(visible.reduce((sum, district) => sum + district.total_colleges, 0))}</strong><small>{districtSlug ? 'Selected district' : `${districts.length} reporting districts`}</small></div></section>
    <section className="college-kpis">{categories.map((category, index) => <article key={category}><i style={{ background: colours[index] }}/><span>{category} colleges</span><strong>{format(totals[category])}</strong><small>{format(seatTotals[category])} available seats</small></article>)}</section>
    <section className="college-filters"><DistrictCombobox districts={districts} value={districtSlug} onChange={setDistrictSlug} label="Filter district"/><label>Institution type<select value={institution} onChange={event => setInstitution(event.target.value)}><option>All</option>{categories.map(category => <option key={category}>{category}</option>)}</select></label><label>Table ranking<select value={sortBy} onChange={event => setSortBy(event.target.value)}><option value="total_colleges">Total institutions</option><option value="total_college_seats">Available seats</option>{categories.map(category => <option key={category} value={category}>{category} colleges</option>)}</select></label></section>
    <section className="college-main-charts"><article className="education-chart-card"><h3>Institution count by type</h3><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={categories.map(name => ({ name, value: totals[name] })).filter(item => item.value)} dataKey="value" nameKey="name" innerRadius={65} outerRadius={99} paddingAngle={2}>{categories.map((name, index) => <Cell key={name} fill={colours[index]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{ fontSize: 10 }}/></PieChart></ResponsiveContainer></article><article className="education-chart-card"><h3>Institution mix by district</h3><ResponsiveContainer width="100%" height={290}><BarChart data={stacked} margin={{ left: -18, right: 3 }}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tickFormatter={value => value.split(' ')[0]} tick={{ fontSize: 9 }}/><YAxis tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{ fontSize: 9 }}/>{categories.map((category, index) => <Bar key={category} dataKey={category} stackId="colleges" fill={colours[index]}/>)}</BarChart></ResponsiveContainer></article><article className="education-chart-card"><h3>Available seats by stream</h3><ResponsiveContainer width="100%" height={290}><Treemap data={categories.map(name => ({ name, value: seatTotals[name] })).filter(item => item.value)} dataKey="value" aspectRatio={4 / 3} content={<TreeTile/>}><Tooltip contentStyle={tooltipStyle} formatter={format}/></Treemap></ResponsiveContainer></article></section>
    <section className="college-ranking-card"><div><h2>District rankings</h2><p>Top 10 districts by {institution === 'All' ? 'total institutions' : `${institution.toLowerCase()} colleges`}. Select a bar to open its district profile.</p></div><ResponsiveContainer width="100%" height={330}><BarChart data={ranking} layout="vertical" margin={{ left: 10, right: 20 }}><CartesianGrid horizontal={false} stroke="#eee6dc"/><XAxis type="number" tick={{ fontSize: 10 }}/><YAxis type="category" dataKey="name" width={115} tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Bar dataKey="value" fill="#6c3cf0" radius={[0, 7, 7, 0]} onClick={entry => entry?.slug && navigate(`/education/districts/${entry.slug}`)}/></BarChart></ResponsiveContainer><div className="ranking-chips">{ranking.slice().reverse().slice(0, 3).map((district, index) => <button onClick={() => navigate(`/education/districts/${district.slug}`)} key={district.slug}><span>#{index + 1}</span>{district.name}<b>{format(district.value)}</b></button>)}</div></section>
    <section className="college-table-card"><div className="college-table-title"><div><h2>District-wise higher education table</h2><p>Click a district row to view its full Education Analytics profile.</p></div><span>{sorted.length} districts shown</span></div><div className="college-table-wrap"><table><thead><tr><th>District</th><th>Institutions</th><th>Seats</th>{categories.map(category => <th key={category}>{category}</th>)}</tr></thead><tbody>{sorted.map(district => <tr key={district.slug} onClick={() => navigate(`/education/districts/${district.slug}`)}><td><b>{district.name}</b><small>View district analytics →</small></td><td>{format(district.total_colleges)}</td><td>{format(district.total_college_seats)}</td>{categories.map(category => <td key={category}>{format(district.college_distribution[category])}</td>)}</tr>)}</tbody></table></div></section>
  </div>
}
