import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, Cell, Legend, Pie, PieChart, Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getDistricts } from '../api'

const number = value => new Intl.NumberFormat('en-IN').format(value || 0)
const measureCards = [['births', 'Total births'], ['deaths', 'Total deaths'], ['births_male', 'Male births'], ['births_female', 'Female births']]
const registration = district => [{name:'Gram Panchayat', value:district.gram_panchayat_births, colour:'#4ba68e'}, {name:'Municipality', value:district.municipality_births, colour:'#f1a446'}, {name:'Corporation', value:district.corporation_births, colour:'#7454cf'}]

export default function CompareDistricts() {
  const [districts, setDistricts] = useState([]), [firstSlug, setFirstSlug] = useState(''), [secondSlug, setSecondSlug] = useState(''), [status, setStatus] = useState('loading')
  useEffect(() => { getDistricts().then(items => { const safeItems = Array.isArray(items) ? items : []; setDistricts(safeItems); setFirstSlug(safeItems[0]?.slug || ''); setSecondSlug(safeItems[1]?.slug || ''); setStatus('ready') }).catch(() => setStatus('error')) }, [])
  const [first, second] = useMemo(() => [districts.find(d => d.slug === firstSlug), districts.find(d => d.slug === secondSlug)], [districts, firstSlug, secondSlug])
  if (status === 'loading') return <div className="loading">Loading district comparison…</div>
  if (status === 'error') return <div className="notice">Comparison data could not load. Check that Django is running on port 8002, then refresh this page.</div>
  if (!first || !second) return <div className="notice">At least two imported district records are required for comparison.</div>
  const comparison = [{name:'Births', [first.name]:first.births, [second.name]:second.births}, {name:'Deaths', [first.name]:first.deaths, [second.name]:second.deaths}]
  const sex = [{name:'Male', [first.name]:first.births_male, [second.name]:second.births_male}, {name:'Female', [first.name]:first.births_female, [second.name]:second.births_female}]
  const radar = [{metric:'Births', a:first.births, b:second.births}, {metric:'Deaths', a:first.deaths, b:second.deaths}, {metric:'GP births', a:first.gram_panchayat_births, b:second.gram_panchayat_births}, {metric:'Municipality', a:first.municipality_births, b:second.municipality_births}, {metric:'Corporation', a:first.corporation_births, b:second.corporation_births}]
  return <><section className="page-title compare-title"><p className="eyebrow">Side-by-side analysis</p><h1>Compare districts</h1><p>Contrast vital-registration counts and registration-area mix.</p><div className="compare-controls"><label>Select District 1<select value={firstSlug} onChange={e => setFirstSlug(e.target.value)}>{districts.map(d => <option key={d.slug} value={d.slug}>{d.name}</option>)}</select></label><span>VS</span><label>Select District 2<select value={secondSlug} onChange={e => setSecondSlug(e.target.value)}>{districts.map(d => <option key={d.slug} value={d.slug}>{d.name}</option>)}</select></label></div></section>
    <section className="compare-kpis">{measureCards.map(([field, label]) => <article key={field}><span>{label}</span><div><b>{number(first[field])}</b><i>vs</i><b>{number(second[field])}</b></div><small>{first.name} <em>·</em> {second.name}</small></article>)}<article><span>Birth : death ratio</span><div><b>{first.deaths ? (first.births/first.deaths).toFixed(2) : '—'} : 1</b><i>vs</i><b>{second.deaths ? (second.births/second.deaths).toFixed(2) : '—'} : 1</b></div><small>{first.name} <em>·</em> {second.name}</small></article><article><span>Registration areas</span><div><b>{first.gram_panchayats + first.municipalities + first.municipal_corporations}</b><i>vs</i><b>{second.gram_panchayats + second.municipalities + second.municipal_corporations}</b></div><small>Local bodies recorded</small></article></section>
    <section className="compare-grid"><article className="compare-chart"><p className="eyebrow">Events</p><h2>Births vs deaths</h2><div><ResponsiveContainer><BarChart data={comparison}><XAxis dataKey="name"/><YAxis tickFormatter={v => `${Math.round(v/1000)}k`}/><Tooltip formatter={number}/><Legend/><Bar dataKey={first.name} fill="#704bd4" radius={[7,7,0,0]}/><Bar dataKey={second.name} fill="#f29a49" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="compare-chart"><p className="eyebrow">Sex distribution</p><h2>Male vs female births</h2><div><ResponsiveContainer><BarChart data={sex}><XAxis dataKey="name"/><YAxis tickFormatter={v => `${Math.round(v/1000)}k`}/><Tooltip formatter={number}/><Legend/><Bar dataKey={first.name} fill="#447ff2" radius={[7,7,0,0]}/><Bar dataKey={second.name} fill="#ec69a3" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="compare-chart radar-card"><p className="eyebrow">Overall shape</p><h2>Registration comparison</h2><div><ResponsiveContainer><RadarChart data={radar}><PolarGrid/><PolarAngleAxis dataKey="metric" tick={{fontSize:11}}/><Radar dataKey="a" name={first.name} stroke="#704bd4" fill="#704bd4" fillOpacity={.26}/><Radar dataKey="b" name={second.name} stroke="#f29a49" fill="#f29a49" fillOpacity={.24}/><Legend/></RadarChart></ResponsiveContainer></div></article><article className="compare-chart"><p className="eyebrow">Registration type</p><h2>Birth distribution</h2><div className="dual-donut"><section><ResponsiveContainer><PieChart><Pie data={registration(first)} dataKey="value" innerRadius={38} outerRadius={66}>{registration(first).map(item => <Cell fill={item.colour} key={item.name}/>)}</Pie><Tooltip formatter={number}/></PieChart></ResponsiveContainer><b>{first.name}</b></section><section><ResponsiveContainer><PieChart><Pie data={registration(second)} dataKey="value" innerRadius={38} outerRadius={66}>{registration(second).map(item => <Cell fill={item.colour} key={item.name}/>)}</Pie><Tooltip formatter={number}/></PieChart></ResponsiveContainer><b>{second.name}</b></section></div></article></section>
  </>
}
