import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Bar, BarChart, Cell, Legend, Pie, PieChart, PolarAngleAxis, PolarGrid, Radar, RadarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getDistrict } from '../api'
import '../district-detail.css'
import '../district-detail-extra.css'

const number = value => new Intl.NumberFormat('en-IN').format(value || 0)
const typeLabels = { gram_panchayat: 'Gram Panchayat', municipality: 'Municipality', corporation: 'Municipal Corporation' }
const colors = { gram_panchayat: '#72ad73', municipality: '#4d7fdc', corporation: '#ad68d0' }

function DetailPanel({ eyebrow, title, children, className = '' }) { return <article className={`detail-panel ${className}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</article> }

export default function DistrictDetail() {
  const { slug } = useParams(), [district, setDistrict] = useState(null), [error, setError] = useState(''), [query, setQuery] = useState(''), [sort, setSort] = useState('births'), [page, setPage] = useState(1)
  useEffect(() => { setDistrict(null); getDistrict(slug).then(setDistrict).catch(e => setError(e.message)) }, [slug])
  const bodies = district?.local_bodies || []
  const groups = useMemo(() => ({ gram_panchayat: bodies.filter(b => b.body_type === 'gram_panchayat'), municipality: bodies.filter(b => b.body_type === 'municipality'), corporation: bodies.filter(b => b.body_type === 'corporation') }), [bodies])
  const distribution = useMemo(() => Object.entries(groups).map(([type, items]) => ({ type, name: typeLabels[type], color: colors[type], births: items.reduce((sum, b) => sum + b.births, 0), deaths: items.reduce((sum, b) => sum + b.deaths, 0), count: items.length })), [groups])
  const topGramPanchayats = useMemo(() => [...groups.gram_panchayat].sort((a,b) => b.births-a.births).slice(0,10), [groups])
  const topByType = type => [...groups[type]].sort((a,b) => b.births-a.births).slice(0,6)
  const filtered = useMemo(() => bodies.filter(body => body.name.toLowerCase().includes(query.toLowerCase())).sort((a,b) => typeof a[sort] === 'string' ? a[sort].localeCompare(b[sort]) : b[sort]-a[sort]), [bodies, query, sort])
  const rows = filtered.slice((page - 1) * 10, page * 10), pages = Math.max(1, Math.ceil(filtered.length / 10))
  const exportCsv = () => { const header = ['Local Body Name','Type','Birth Count','Death Count','Male Births','Female Births']; const data = filtered.map(b => [b.name,typeLabels[b.body_type],b.births,b.deaths,b.births_male,b.births_female].map(v => `"${v}"`).join(',')); const url = URL.createObjectURL(new Blob([[header.join(','),...data].join('\n')], {type:'text/csv'})); const link = document.createElement('a'); link.href=url; link.download=`${district.slug}-local-body-registration-data.csv`; link.click(); URL.revokeObjectURL(url) }
  if (error) return <div className="notice">{error}</div>
  if (!district) return <div className="loading">Loading district registration analytics…</div>
  const kpis = [['Total births',district.births,'#7047d4'],['Total deaths',district.deaths,'#ee7b66'],['Male births',district.births_male,'#4e80e9'],['Female births',district.births_female,'#e86b9e'],['Birth : death ratio',district.deaths ? `${(district.births/district.deaths).toFixed(2)} : 1`:'—','#e6a13f'],['Registration centres',distribution.reduce((sum,item) => sum+item.count,0),'#6daa7a']]
  const eventData = [{name:'Registered events', Births:district.births, Deaths:district.deaths}]
  const sexData = [{name:'Male births',value:district.births_male,color:'#4e80e9'},{name:'Female births',value:district.births_female,color:'#e86b9e'}]
  const contribution = [{name:'Births',...Object.fromEntries(distribution.map(item => [item.name,item.births]))},{name:'Deaths',...Object.fromEntries(distribution.map(item => [item.name,item.deaths]))}]
  const highestGramPanchayat = topGramPanchayats[0]
  const registrationBirths = distribution.reduce((sum, item) => sum + item.births, 0)
  const radarData = [
    { metric: 'Births', value: district.births }, { metric: 'Deaths', value: district.deaths },
    { metric: 'Male births', value: district.births_male }, { metric: 'Female births', value: district.births_female },
    ...distribution.map(item => ({ metric: item.name, value: item.births })),
  ]
  return <div className="district-analytics"><Link className="back-link" to="/demographics/districts">← District table</Link><section className="district-hero"><div><p className="eyebrow">District registration analytics</p><h1>{district.name}</h1><p>Birth and death registration insights from the uploaded Telangana workbook.</p><div className="district-hero-tags"><span>{distribution[0].count} Gram Panchayats</span><span>{distribution[1].count} Municipalities</span><span>{distribution[2].count} Corporations</span></div></div><div className="district-art"><span>{district.name.slice(0,2).toUpperCase()}</span><small>Telangana<br/>Registration Portal</small></div></section>
    <section className="detail-kpis">{kpis.map(([label,value,color]) => <article key={label} style={{'--accent':color}}><span>{label}</span><strong>{typeof value === 'number' ? number(value) : value}</strong></article>)}</section>
    <section className="local-summary">{distribution.map(item => <article key={item.type}><div><i style={{background:item.color}}/><span>{item.name}</span><b>{number(item.count)} bodies</b></div><p><strong>{number(item.births)}</strong> births</p><p><strong>{number(item.deaths)}</strong> deaths</p></article>)}</section>
    <section className="detail-insights"><DetailPanel eyebrow="Quick insights" title="District registration signals"><div className="insight-cards"><article><span>◆</span><p>Highest contributing Gram Panchayat<b>{highestGramPanchayat?.name || 'No data'}</b><small>{number(highestGramPanchayat?.births)} registered births</small></p></article><article><span>↗</span><p>Births exceed deaths by<b>{district.deaths ? `${(((district.births-district.deaths)/district.deaths)*100).toFixed(1)}%` : '—'}</b><small>Based on district totals</small></p></article><article><span>◉</span><p>Male to female birth ratio<b>{district.births_female ? `${(district.births_male/district.births_female).toFixed(2)} : 1` : '—'}</b><small>Registered birth records</small></p></article><article><span>▣</span><p>Largest registration type<b>{[...distribution].sort((a,b) => b.births-a.births)[0]?.name || '—'}</b><small>{registrationBirths ? `${((Math.max(...distribution.map(item => item.births))/registrationBirths)*100).toFixed(1)}% of type-level births` : 'No data'}</small></p></article></div></DetailPanel></section>
    <section className="detail-grid top-detail-grid"><DetailPanel eyebrow="Sex distribution" title="Male vs female births"><div className="detail-chart sex-donut"><ResponsiveContainer><PieChart><Pie data={sexData} dataKey="value" innerRadius={48} outerRadius={79} paddingAngle={3}>{sexData.map(item => <Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={number}/></PieChart></ResponsiveContainer><div>{sexData.map(item => <span key={item.name}><i style={{background:item.color}}/>{item.name}<b>{number(item.value)}</b></span>)}</div></div></DetailPanel><DetailPanel eyebrow="Registered events" title="Births vs deaths"><div className="detail-chart"><ResponsiveContainer><BarChart data={eventData}><XAxis dataKey="name" hide/><YAxis tickFormatter={v => `${Math.round(v/1000)}k`}/><Tooltip formatter={number}/><Legend/><Bar dataKey="Births" fill="#744bd7" radius={[9,9,0,0]}/><Bar dataKey="Deaths" fill="#f0a04b" radius={[9,9,0,0]}/></BarChart></ResponsiveContainer></div></DetailPanel><DetailPanel eyebrow="Registration types" title="Birth distribution"><div className="detail-chart type-donut"><ResponsiveContainer><PieChart><Pie data={distribution} dataKey="births" innerRadius={48} outerRadius={79} paddingAngle={3}>{distribution.map(item => <Cell key={item.type} fill={item.color}/>)}</Pie><Tooltip formatter={number}/></PieChart></ResponsiveContainer><div>{distribution.map(item => <span key={item.type}><i style={{background:item.color}}/>{item.name}<b>{number(item.births)}</b></span>)}</div></div></DetailPanel></section>
    <section className="detail-grid"><DetailPanel eyebrow="Gram Panchayats" title="Top 10 by birth count" className="wide-chart"><div className="detail-chart"><ResponsiveContainer><BarChart data={topGramPanchayats} layout="vertical" margin={{left:10}}><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={130} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip formatter={number}/><Bar dataKey="births" fill="#70ab73" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></div></DetailPanel><DetailPanel eyebrow="Local body contribution" title="Births & deaths by type"><div className="detail-chart"><ResponsiveContainer><BarChart data={contribution}><XAxis dataKey="name"/><YAxis tickFormatter={v => `${Math.round(v/1000)}k`}/><Tooltip formatter={number}/><Legend/><Bar dataKey="Gram Panchayat" stackId="local" fill="#70ab73"/><Bar dataKey="Municipality" stackId="local" fill="#4d7fdc"/><Bar dataKey="Municipal Corporation" stackId="local" fill="#ae68d0" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></DetailPanel></section>
    <section className="detail-grid"><DetailPanel eyebrow="Municipalities" title="Births vs deaths"><div className="detail-chart"><ResponsiveContainer><BarChart data={topByType('municipality')} layout="vertical" margin={{left:8}}><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={120} tick={{fontSize:10}}/><Tooltip formatter={number}/><Legend/><Bar dataKey="births" name="Births" fill="#4d7fdc" radius={[0,6,6,0]}/><Bar dataKey="deaths" name="Deaths" fill="#f0a04b" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></DetailPanel><DetailPanel eyebrow="Municipal corporations" title="Births vs deaths"><div className="detail-chart"><ResponsiveContainer><BarChart data={topByType('corporation')} layout="vertical" margin={{left:8}}><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={130} tick={{fontSize:10}}/><Tooltip formatter={number}/><Legend/><Bar dataKey="births" name="Births" fill="#ae68d0" radius={[0,6,6,0]}/><Bar dataKey="deaths" name="Deaths" fill="#f0a04b" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></div></DetailPanel></section>
    <section className="detail-grid"><DetailPanel eyebrow="District performance" title="Registration profile"><div className="detail-chart"><ResponsiveContainer><RadarChart data={radarData}><PolarGrid/><PolarAngleAxis dataKey="metric" tick={{fontSize:10}}/><Radar dataKey="value" name="Registered records" stroke="#744bd7" fill="#744bd7" fillOpacity={.32}/><Tooltip formatter={number}/></RadarChart></ResponsiveContainer></div></DetailPanel><DetailPanel eyebrow="Registration contribution" title="Birth distribution by type"><div className="detail-chart contribution-breakdown">{distribution.map(item => <div key={item.type}><div><i style={{background:item.color}}/><span>{item.name}</span><b>{registrationBirths ? `${((item.births/registrationBirths)*100).toFixed(1)}%` : '0%'}</b></div><p><i style={{width:`${registrationBirths ? (item.births/registrationBirths)*100 : 0}%`,background:item.color}}/></p><small>{number(item.births)} births · {number(item.deaths)} deaths</small></div>)}</div></DetailPanel></section>
    <section className="local-table-section"><div className="table-title"><div><p className="eyebrow">Local body records</p><h2>Detailed registration data</h2></div><div><input value={query} onChange={e => {setQuery(e.target.value);setPage(1)}} placeholder="Search local body"/><button onClick={exportCsv}>↓ Export CSV</button></div></div><div className="table-wrap"><table><thead><tr>{[['name','Local body name'],['body_type','Type'],['births','Birth count'],['deaths','Death count'],['births_male','Male births'],['births_female','Female births']].map(([field,label]) => <th key={field}><button onClick={() => {setSort(field);setPage(1)}}>{label} ↕</button></th>)}</tr></thead><tbody>{rows.map(body => <tr key={body.id}><td>{body.name}</td><td><span className="body-type">{typeLabels[body.body_type]}</span></td><td>{number(body.births)}</td><td>{number(body.deaths)}</td><td>{number(body.births_male)}</td><td>{number(body.births_female)}</td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing {rows.length} of {filtered.length} local bodies</span><div><button disabled={page===1} onClick={() => setPage(p=>p-1)}>←</button><b>{page} / {pages}</b><button disabled={page===pages} onClick={() => setPage(p=>p+1)}>→</button></div></div></section>
  </div>
}
