import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'
import { getEducationOverview } from '../api'
import EducationMap from '../components/EducationMap'
import '../education-dashboard.css'

const format = value => new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 }).format(value || 0)
const palette = ['#6c3cf0', '#9d5ce6', '#f59e0b', '#ec4899', '#4e9ce6', '#4ba879']
const ChartCard = ({ title, children, className = '' }) => <section className={`education-chart-card ${className}`}><h3>{title}</h3>{children}</section>
const tooltipStyle = { borderRadius: 12, border: '1px solid #eee2d6', boxShadow: '0 10px 24px #41206e1f' }

export default function EducationOverview() {
  const [data, setData] = useState(null), [error, setError] = useState(''), [layer, setLayer] = useState('literacy')
  useEffect(() => { getEducationOverview().then(setData).catch(e => setError(e.message)) }, [])
  const districts = data?.districts || []
  const stats = useMemo(() => {
    const by = (field, direction = -1) => [...districts].sort((a, b) => direction * ((a[field] || 0) - (b[field] || 0)))[0]
    return { highLiteracy: by('literacy_rate'), lowLiteracy: by('literacy_rate', 1), highEnrollment: by('total_enrollment'), engineering: by('engineering_college_seats'), schools: by('total_schools') }
  }, [districts])
  const topLiteracy = [...districts].sort((a, b) => b.literacy_rate - a.literacy_rate).slice(0, 8).reverse()
  const topEnrollment = [...districts].sort((a, b) => b.total_enrollment - a.total_enrollment).slice(0, 6)
  const schoolMix = districts.reduce((total, district) => Object.entries(district.school_distribution).reduce((next, [key, value]) => ({ ...next, [key]: (next[key] || 0) + value }), total), {})
  const collegeMix = districts.reduce((total, district) => Object.entries(district.college_distribution).reduce((next, [key, value]) => ({ ...next, [key]: (next[key] || 0) + value }), total), {})
  const collegeSeats = districts.reduce((total, district) => Object.entries(district.college_seat_distribution).reduce((next, [key, value]) => ({ ...next, [key]: (next[key] || 0) + value }), total), {})
  if (!data && !error) return <div className="loading">Loading Telangana education statistics…</div>
  if (error) return <div className="notice">{error} Start Django and run migrations to load the supplied education datasets.</div>
  return <div className="education-overview" id="education-dashboard">
    <section className="education-hero"><div><p className="eyebrow">Home · Education analytics</p><h1>Education Statistics Dashboard</h1><p>Government of Telangana · District literacy, schools, enrollment and higher-education capacity in one view.</p></div><div className="education-hero-mark"><span>✦</span><b>Education<br/>for every learner</b></div></section>
    <section className="kpis kpis-five education-kpis"><article><span>Total schools</span><strong>{format(data.total_schools)}</strong><small>Across reporting districts</small></article><article><span>Total colleges</span><strong>{format(data.total_colleges)}</strong><small>All available types</small></article><article><span>Total enrollment</span><strong>{format(data.total_enrollment)}</strong><small>School enrollment</small></article><article><span>Male literacy</span><strong>{data.male_literacy_rate.toFixed(2)}%</strong><small>Weighted district rate</small></article><article><span>Female literacy</span><strong>{data.female_literacy_rate.toFixed(2)}%</strong><small>Weighted district rate</small></article></section>
    <section className="education-main" id="education-literacy">
      <div className="education-side"><ChartCard title="Top literacy districts"><ResponsiveContainer width="100%" height={250}><BarChart data={topLiteracy} layout="vertical" margin={{ left: 8, right: 8 }}><CartesianGrid horizontal={false} stroke="#eee6dc"/><XAxis type="number" tickFormatter={v => `${v}%`} tick={{ fontSize: 10 }}/><YAxis dataKey="name" type="category" width={86} tick={{ fontSize: 10 }}/><Tooltip formatter={v => `${v.toFixed(2)}%`} contentStyle={tooltipStyle}/><Bar dataKey="literacy_rate" fill="#6c3cf0" radius={[0, 8, 8, 0]}/></BarChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Male vs female literacy"><ResponsiveContainer width="100%" height={230}><BarChart data={topEnrollment.slice(0, 5)} margin={{ left: -22, right: 4 }}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tickFormatter={v => v.split(' ')[0]} tick={{ fontSize: 9 }}/><YAxis tickFormatter={v => `${v}%`} tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={v => `${v.toFixed(2)}%`}/><Legend wrapperStyle={{ fontSize: 10 }}/><Bar dataKey="male_literacy_rate" name="Male" fill="#6c3cf0" radius={[5, 5, 0, 0]}/><Bar dataKey="female_literacy_rate" name="Female" fill="#ec4899" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></ChartCard></div>
      <section className="education-map-card"><div className="map-card-heading"><div><h2>Telangana education map</h2><p>Choose a layer, hover for district details, or click to open district analytics.</p></div><div className="education-layer-pills">{[['literacy', 'Literacy'], ['maleLiteracy', 'Male literacy'], ['femaleLiteracy', 'Female literacy'], ['schools', 'Schools'], ['enrollment', 'Enrollment'], ['colleges', 'Colleges']].map(([key, label]) => <button className={layer === key ? 'active' : ''} onClick={() => setLayer(key)} key={key}>{label}</button>)}</div></div><EducationMap districts={districts} layer={layer}/></section>
      <div className="education-side"><ChartCard title="School distribution"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={Object.entries(schoolMix).map(([name, value]) => ({ name, value })).filter(d => d.value)} dataKey="value" nameKey="name" innerRadius={48} outerRadius={78} paddingAngle={2}>{Object.entries(schoolMix).map(([,], i) => <Cell key={i} fill={palette[i % palette.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend layout="vertical" align="right" verticalAlign="middle" wrapperStyle={{ fontSize: 10 }}/></PieChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Enrollment by district"><ResponsiveContainer width="100%" height={250}><BarChart data={topEnrollment} margin={{ left: -18, right: 4 }}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tickFormatter={v => v.split(' ')[0]} tick={{ fontSize: 9 }}/><YAxis tickFormatter={v => `${Math.round(v / 1000)}k`} tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Bar dataKey="total_enrollment" fill="#f59e0b" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer></ChartCard></div>
    </section>
    <section className="education-secondary" id="education-colleges"><ChartCard title="College distribution"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={Object.entries(collegeMix).map(([name, value]) => ({ name, value })).filter(d => d.value)} dataKey="value" nameKey="name" outerRadius={78} paddingAngle={2}>{Object.entries(collegeMix).map(([,], i) => <Cell key={i} fill={palette[i % palette.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{ fontSize: 10 }}/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="College seats by stream"><ResponsiveContainer width="100%" height={220}><BarChart data={Object.entries(collegeSeats).map(([name, seats]) => ({ name, seats })).filter(d => d.seats)} margin={{ left: -18, right: 4 }}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tick={{ fontSize: 9 }}/><YAxis tickFormatter={v => `${Math.round(v / 1000)}k`} tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Bar dataKey="seats" fill="#9d5ce6" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Enrollment trends by school stage"><ResponsiveContainer width="100%" height={220}><BarChart data={Object.entries(districts.reduce((total, d) => Object.entries(d.enrollment_distribution).reduce((next, [key, value]) => ({ ...next, [key]: (next[key] || 0) + value }), total), {})).map(([name, enrollment]) => ({ name, enrollment }))} margin={{ left: -18, right: 4 }}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tick={{ fontSize: 9 }}/><YAxis tickFormatter={v => `${Math.round(v / 1000)}k`} tick={{ fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Bar dataKey="enrollment" fill="#4e9ce6" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer></ChartCard></section>
    <section className="education-summary" id="education-infrastructure"><h2>Education summary</h2><div>{[["Highest literacy", stats.highLiteracy, 'literacy_rate', '%'], ["Lowest literacy", stats.lowLiteracy, 'literacy_rate', '%'], ["Highest enrollment", stats.highEnrollment, 'total_enrollment', ''], ["Most engineering seats", stats.engineering, 'engineering_college_seats', ''], ["Largest school network", stats.schools, 'total_schools', '']].map(([title, district, key, suffix]) => <article key={title}><span>{title}</span><strong>{district?.name || '—'}</strong><b>{key.includes('rate') ? `${district?.[key]?.toFixed(2) || 0}${suffix}` : `${format(district?.[key])}${suffix}`}</b></article>)}</div></section>
    <section className="education-bottom" id="education-rankings"><ChartCard title="Quick insights"><ul className="education-insights"><li><b>{stats.highLiteracy?.name}</b> leads the available dataset in overall literacy at <strong>{stats.highLiteracy?.literacy_rate.toFixed(2)}%</strong>.</li><li><b>{stats.highEnrollment?.name}</b> has the highest recorded school enrollment ({format(stats.highEnrollment?.total_enrollment)} learners).</li><li><b>{stats.schools?.name}</b> has the widest school network with {format(stats.schools?.total_schools)} institutions.</li><li>Female literacy is <b>{data.female_literacy_rate.toFixed(2)}%</b> across reporting districts, compared with <b>{data.male_literacy_rate.toFixed(2)}%</b> for male literacy.</li></ul></ChartCard><ChartCard title="District literacy rankings"><div className="ranking-preview"><div><h4>Top 5</h4>{districts.slice(0, 5).map(d => <p key={d.slug}><span>{d.state_rank}. {d.name}</span><b>{d.literacy_rate.toFixed(2)}%</b></p>)}</div><div><h4>Bottom 5</h4>{districts.slice(-5).reverse().map(d => <p key={d.slug}><span>{d.state_rank}. {d.name}</span><b>{d.literacy_rate.toFixed(2)}%</b></p>)}</div></div><Link className="education-view-all" to="#education-rankings">View all rankings →</Link></ChartCard></section>
  </div>
}
