import { useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts'
import { Link, useParams } from 'react-router-dom'
import { getEducationMultiYearOverview } from '../api'
import '../education-dashboard.css'

const palette=['#6c3cf0','#9d5ce6','#f59e0b','#ec4899','#4e9ce6','#4ba879','#c18c4e','#8b6dca']
const format=value=>value==null?'—':new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(value)
const chartTooltip={borderRadius:12,border:'1px solid #eee2d6',boxShadow:'0 10px 24px #41206e1f'}
const ChartCard=({title,children,className=''})=><section className={`education-chart-card ${className}`}><h3>{title}</h3>{children}</section>
const distribution=(data={})=>Object.entries(data).filter(([,value])=>value).map(([name,value])=>({name,value}))
function Donut({data}) { return data.length?<ResponsiveContainer width="100%" height={252}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88} paddingAngle={2}>{data.map((item,index)=><Cell key={item.name} fill={palette[index%palette.length]}/>)}</Pie><Tooltip contentStyle={chartTooltip} formatter={format}/><Legend wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer>:<p className="comparison-note">Not supplied for this reporting year.</p> }
function Column({data,valueKey='value',colour='#6c3cf0'}) { return data.length?<ResponsiveContainer width="100%" height={252}><BarChart data={data} margin={{left:-18,right:4}}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tickFormatter={value=>`${Math.round(value/1000)}k`} tick={{fontSize:10}}/><Tooltip contentStyle={chartTooltip} formatter={format}/><Bar dataKey={valueKey} fill={colour} radius={[7,7,0,0]}/></BarChart></ResponsiveContainer>:<p className="comparison-note">Not supplied for this reporting year.</p> }
const rank=(districts,field,slug)=>{const list=districts.filter(item=>item[field]!=null).sort((a,b)=>b[field]-a[field]);const position=list.findIndex(item=>item.slug===slug);return position<0?null:{position:position+1,total:list.length}}

export default function EducationDistrictAnalytics() {
  const {slug}=useParams(); const [data,setData]=useState(null),[error,setError]=useState(''),[year,setYear]=useState('All Years')
  useEffect(()=>{getEducationMultiYearOverview().then(setData).catch(item=>setError(item.message))},[])
  const annual=data?.annual||[], selected=year==='All Years'?null:data?.by_year?.[year]
  const records=useMemo(()=>annual.map(item=>({year:item.year,district:item.districts.find(entry=>entry.slug===slug),districts:item.districts})).filter(item=>item.district),[annual,slug])
  const district=selected?.districts.find(item=>item.slug===slug)
  if(!data&&!error)return <div className="loading">Loading district education analytics…</div>
  if(error)return <div className="notice">{error}</div>
  if(!records.length)return <div className="notice">This district is not present in the supplied multi-year datasets.</div>
  const name=records[0].district.name
  return <div className="education-district"><Link className="back-link" to="/education">← Education dashboard</Link><section className="district-profile-hero"><div className="district-profile-art" aria-hidden="true"><span>✦</span><i/><i/><i/></div><div className="district-profile-copy"><p className="eyebrow">Education profile · Telangana</p><h1>{name}</h1><h2>District Education Profile</h2><p>School, enrollment and higher-education analytics from the supplied year-labelled government datasets.</p></div><div className="education-score"><span>Reporting years</span><strong>{records.length}</strong><small>available for this district</small><b>{year==='All Years'?'Multi-year view':year}</b></div></section><section className="education-year-control"><label htmlFor="district-year">Reporting year</label><select id="district-year" value={year} onChange={event=>setYear(event.target.value)}><option>All Years</option>{annual.map(item=><option key={item.year}>{item.year}</option>)}</select><span>{year==='All Years'?'Trend and comparison view':'Detailed selected-year analytics'}</span></section>{selected?<YearDetail district={district} yearData={selected}/>:<AllYears records={records}/>}</div>
}

function AllYears({records}) {
  const trend=records.map(({year,district})=>({year,schools:district.total_schools,enrollment:district.total_enrollment,colleges:district.total_colleges,seats:district.total_college_seats}))
  const categoryKeys=[...new Set(records.flatMap(item=>Object.keys(item.district.school_distribution||{})))], categoryData=records.map(({year,district})=>({year,...Object.fromEntries(categoryKeys.map(key=>[key,district.school_distribution?.[key]??null]))}))
  const scatterData=records.filter(item=>item.district.total_schools!=null&&item.district.total_enrollment!=null).map(({year,district})=>({year,schools:district.total_schools,enrollment:district.total_enrollment}))
  const latest=records.at(-1), earliest=records[0]
  const change=(field)=>{const first=earliest.district[field],last=latest.district[field];return first==null||last==null||!first?null:((last-first)/first)*100}
  const schoolChange=change('total_schools'), enrollmentChange=change('total_enrollment')
  const comparison=field=>records.map(({year,district})=>({year,value:district[field],average:averageForYear(records,year,field)}))
  const recommendation=[]
  if(schoolChange!=null&&schoolChange<0)recommendation.push(`Review the ${Math.abs(schoolChange).toFixed(1)}% change in reported schools between the first and latest available district reports.`)
  if(enrollmentChange!=null&&enrollmentChange>0)recommendation.push(`Plan capacity against the ${enrollmentChange.toFixed(1)}% change in recorded enrollment across the available reports.`)
  if(!recommendation.length)recommendation.push('Continue monitoring the supplied reporting-year trends before making capacity decisions.')
  return <><section className="kpis kpis-six education-kpis district-kpis"><Kpi title="Latest schools" value={latest.district.total_schools} note={latest.year}/><Kpi title="Latest enrollment" value={latest.district.total_enrollment} note={latest.year}/><Kpi title="Latest colleges" value={latest.district.total_colleges} note={latest.year}/><Kpi title="College seats" value={latest.district.total_college_seats} note={latest.year}/><Kpi title="School change" value={schoolChange==null?'—':`${schoolChange>=0?'+':''}${schoolChange.toFixed(1)}%`} note="First to latest reported"/><Kpi title="Enrollment change" value={enrollmentChange==null?'—':`${enrollmentChange>=0?'+':''}${enrollmentChange.toFixed(1)}%`} note="First to latest reported"/></section><section className="district-chart-grid"><Trend title="Enrollment trend across reporting years" data={trend} field="enrollment" colour="#f59e0b"/><InstitutionBars data={trend}/><CategoryBars data={categoryData} keys={categoryKeys}/><EnrollmentScatter data={scatterData}/><ChartCard title={`School distribution · ${latest.year}`}><Donut data={distribution(latest.district.school_distribution)}/></ChartCard><CapacityArea data={trend}/></section><InsightGrid title="All available years" district={latest.district} comparisons={[['Latest schools',latest.district.total_schools,averageForYear(records,latest.year,'total_schools')],['Latest enrollment',latest.district.total_enrollment,averageForYear(records,latest.year,'total_enrollment')],['Latest colleges',latest.district.total_colleges,averageForYear(records,latest.year,'total_colleges')]]} summary={`${latest.district.name} has ${records.length} supplied reporting years. In the latest available report (${latest.year}), it records ${format(latest.district.total_enrollment)} enrollment across ${format(latest.district.total_schools)} schools. Literacy is not included because no annual literacy dataset was supplied.`} recommendations={recommendation}/></>
}
function averageForYear(records,year,field){const items=records.find(item=>item.year===year)?.districts.filter(item=>item[field]!=null)||[];return items.length?items.reduce((sum,item)=>sum+item[field],0)/items.length:null}

function Trend({title,data,field,average=false,colour,className=''}) { return <ChartCard title={title} className={className}><ResponsiveContainer width="100%" height={252}><LineChart data={data}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tickFormatter={value=>`${Math.round(value/1000)}k`} tick={{fontSize:10}}/><Tooltip contentStyle={chartTooltip} formatter={format}/><Line connectNulls type="monotone" dataKey={field} name="District" stroke={colour} strokeWidth={3} dot={{r:4}}/>{average&&<Line connectNulls type="monotone" dataKey="average" name="Telangana average" stroke="#ec4899" strokeWidth={2} strokeDasharray="5 4" dot={false}/>}</LineChart></ResponsiveContainer></ChartCard> }
function InstitutionBars({data}) { return <ChartCard title="Schools and colleges by reporting year"><ResponsiveContainer width="100%" height={252}><BarChart data={data}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip contentStyle={chartTooltip} formatter={format}/><Legend wrapperStyle={{fontSize:10}}/><Bar dataKey="schools" name="Schools" fill="#6c3cf0" radius={[5,5,0,0]}/><Bar dataKey="colleges" name="Colleges" fill="#ec4899" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></ChartCard> }
function CategoryBars({data,keys}) { return <ChartCard title="School categories across reporting years"><ResponsiveContainer width="100%" height={252}><BarChart data={data}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip contentStyle={chartTooltip} formatter={format}/><Legend wrapperStyle={{fontSize:9}}/>{keys.map((key,index)=><Bar key={key} dataKey={key} stackId="schools" fill={palette[index%palette.length]}/>)}</BarChart></ResponsiveContainer></ChartCard> }
function EnrollmentScatter({data}) { return <ChartCard title="Enrollment compared with schools"><ResponsiveContainer width="100%" height={252}><ScatterChart margin={{left:8,right:8,bottom:8}}><CartesianGrid stroke="#eee6dc"/><XAxis type="number" dataKey="schools" name="Schools" tick={{fontSize:10}}/><YAxis type="number" dataKey="enrollment" name="Enrollment" tickFormatter={value=>`${Math.round(value/1000)}k`} tick={{fontSize:10}}/><ZAxis range={[80,80]}/><Tooltip contentStyle={chartTooltip} formatter={format} labelFormatter={(_,items)=>items?.[0]?.payload?.year||''}/><Scatter data={data} fill="#4e9ce6"/></ScatterChart></ResponsiveContainer></ChartCard> }
function CapacityArea({data}) { return <ChartCard title="College-seat capacity where available"><ResponsiveContainer width="100%" height={252}><AreaChart data={data}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="year" tick={{fontSize:10}}/><YAxis tickFormatter={value=>`${Math.round(value/1000)}k`} tick={{fontSize:10}}/><Tooltip contentStyle={chartTooltip} formatter={format}/><Area connectNulls type="monotone" dataKey="seats" name="College seats" stroke="#9d5ce6" fill="#9d5ce655"/></AreaChart></ResponsiveContainer></ChartCard> }
function Kpi({title,value,note}) { return <article><span>{title}</span><strong>{typeof value==='number'?format(value):value}</strong><small>{note}</small></article> }

function YearDetail({district,yearData}) {
  const ranks={schools:rank(yearData.districts,'total_schools',district.slug),enrollment:rank(yearData.districts,'total_enrollment',district.slug),colleges:rank(yearData.districts,'total_colleges',district.slug)}
  const comparisons=[['Schools',district.total_schools,yearAverage(yearData,'total_schools')],['Enrollment',district.total_enrollment,yearAverage(yearData,'total_enrollment')],['Colleges',district.total_colleges,yearAverage(yearData,'total_colleges')],['College seats',district.total_college_seats,yearAverage(yearData,'total_college_seats')]]
  const recommendations=[]
  if(district.total_colleges!=null&&district.total_colleges<(yearAverage(yearData,'total_colleges')||0))recommendations.push('Assess opportunities to strengthen local higher-education access relative to the reporting-district average.')
  if(district.total_enrollment!=null&&district.total_schools!=null&&district.total_enrollment/Math.max(district.total_schools,1)>(yearAverage(yearData,'total_enrollment')||0)/Math.max(yearAverage(yearData,'total_schools')||1,1))recommendations.push('Review school capacity because enrollment per school is above the selected-year reporting-district average.')
  if(!recommendations.length)recommendations.push('Maintain current reporting coverage and monitor district indicators in subsequent supplied years.')
  const badges=[ranks.schools?.position<=5&&'Top school network',ranks.enrollment?.position<=5&&'High enrollment reach',district.total_colleges>0&&'Higher-education reporting'].filter(Boolean)
  return <><section className="achievement-badges district-year-badges">{badges.length?badges.map(item=><span key={item}>✦ {item}</span>):<span>✦ Reporting district</span>}</section><section className="kpis kpis-six education-kpis district-kpis"><Kpi title="Total schools" value={district.total_schools} note="All reported types"/><Kpi title="Total enrollment" value={district.total_enrollment} note="School enrollment"/><Kpi title="Total colleges" value={district.total_colleges} note="Where supplied"/><Kpi title="College seats" value={district.total_college_seats} note="Where supplied"/><Kpi title="School rank" value={ranks.schools?`#${ranks.schools.position}`:'—'} note={ranks.schools?`of ${ranks.schools.total} districts`:'Not supplied'}/><Kpi title="Enrollment rank" value={ranks.enrollment?`#${ranks.enrollment.position}`:'—'} note={ranks.enrollment?`of ${ranks.enrollment.total} districts`:'Not supplied'}/></section><section className="district-ranks"><RankCard title="School rank" rank={ranks.schools}/><RankCard title="Enrollment rank" rank={ranks.enrollment}/><RankCard title="College rank" rank={ranks.colleges}/></section><section className="district-chart-grid"><ChartCard title="School distribution"><Donut data={distribution(district.school_distribution)}/></ChartCard><ChartCard title="Enrollment distribution"><Column data={distribution(district.enrollment_distribution)} colour="#f59e0b"/></ChartCard><ChartCard title="College distribution"><Donut data={distribution(district.college_distribution)}/></ChartCard><ChartCard title="College seats"><Column data={distribution(district.college_seat_distribution)} colour="#9d5ce6"/></ChartCard><ChartCard title="Literacy comparison" className="literacy-comparison"><p className="comparison-note">No year-labelled literacy dataset was supplied for this selected-year analysis.</p></ChartCard></section><InsightGrid title={yearData.year} district={district} comparisons={comparisons} summary={`${district.name} reports ${format(district.total_enrollment)} school enrollment across ${format(district.total_schools)} schools in ${yearData.year}. ${district.total_colleges==null?'College information was not supplied for this year.':`It reports ${format(district.total_colleges)} colleges where available.`} Literacy comparisons are unavailable because the supplied multi-year files do not contain annual literacy values.`} recommendations={recommendations}/></>
}
function yearAverage(data,field){const items=data.districts.filter(item=>item[field]!=null);return items.length?items.reduce((sum,item)=>sum+item[field],0)/items.length:null}
function RankCard({title,rank}) { return <article><span>{title}</span><strong>{rank?`#${rank.position}`:'—'}</strong><small>{rank?`of ${rank.total} reporting districts`:'Not supplied'}</small></article> }
function InsightGrid({title,district,comparisons,summary,recommendations}) { return <section className="district-insight-grid"><ChartCard title="Compare with Telangana average"><div className="comparison-bars">{comparisons.map(([label,value,average])=>{if(value==null||average==null)return <div key={label}><p><span>{label}</span><b>Not supplied</b></p></div>;const width=Math.min((value/Math.max(average*2,1))*100,100);return <div key={label}><p><span>{label}</span><b>{format(value)}</b></p><div className="comparison-track"><i style={{width:`${width}%`}}/><em style={{left:'50%'}}/></div><small>Telangana reporting-district average: {format(average)}</small></div>})}</div></ChartCard><ChartCard title="AI-style district summary"><p className="district-summary">{summary}</p><div className="score-method"><b>Data basis</b><span>Only supplied reporting-year values are included; no missing measures are estimated.</span></div></ChartCard><ChartCard title="Smart recommendations"><ul className="recommendations">{recommendations.map(item=><li key={item}><i>→</i>{item}</li>)}</ul></ChartCard></section> }
