import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { getDistricts } from '../api'
const measures = { births: 'Birth count', deaths: 'Death count', births_male: 'Male births', births_female: 'Female births', deaths_male: 'Male deaths', deaths_female: 'Female deaths', gram_panchayat_births: 'Gram Panchayat births', municipality_births: 'Municipality births', corporation_births: 'Corporation births' }
const formatter = new Intl.NumberFormat('en-IN')
export default function Rankings() {
  const [districts, setDistricts] = useState([]), [measure, setMeasure] = useState('births'), [status, setStatus] = useState('loading')
  useEffect(() => { getDistricts().then(items => { setDistricts(Array.isArray(items) ? items : []); setStatus('ready') }).catch(() => setStatus('error')) }, [])
  const sorted = useMemo(() => [...districts].sort((a,b) => Number(b[measure] || 0) - Number(a[measure] || 0)), [districts, measure])
  const total = sorted.reduce((sum, item) => sum + Number(item[measure] || 0), 0)
  if (status === 'loading') return <div className="loading">Loading district rankings…</div>
  if (status === 'error') return <div className="notice">Rankings could not load. Check that Django is running on port 8002, then refresh this page.</div>
  return <><section className="page-title"><p className="eyebrow">District performance</p><h1>District rankings</h1><p>Change the indicator to identify leading registration areas.</p></section><label className="filter">Rank by <select value={measure} onChange={e => setMeasure(e.target.value)}>{Object.entries(measures).map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label>
    {sorted.length > 0 && <section className="rank-showcase"><article className="podium-card"><p className="eyebrow">Leading three</p><div className="podium">{[sorted[1], sorted[0], sorted[2]].filter(Boolean).map((district, index) => <Link key={district.slug} to={`/districts/${district.slug}`} className={`podium-place place-${index}`}><span>{index === 1 ? '1' : index === 0 ? '2' : '3'}</span><b>{district.name}</b><small>{formatter.format(district[measure] || 0)}</small></Link>)}</div></article><article className="contribution-card"><p className="eyebrow">District contribution</p><h2>Share of {measures[measure]?.toLowerCase() || 'selected measure'}</h2><div className="contribution-strip">{sorted.slice(0,10).map((district, index) => <Link title={`${district.name}: ${total ? ((district[measure]/total)*100).toFixed(1) : 0}%`} key={district.slug} to={`/districts/${district.slug}`} style={{width:`${total ? (district[measure]/total)*100 : 0}%`, background:`hsl(${258-index*13} 66% ${46+index*3}%)`}}>{district.name}</Link>)}</div><div className="contribution-key">{sorted.slice(0,5).map(district => <span key={district.slug}>{district.name} <b>{total ? ((district[measure]/total)*100).toFixed(1) : 0}%</b></span>)}</div></article></section>}
    <section className="ranking-list">{sorted.length ? sorted.map((district, index) => <Link to={`/districts/${district.slug}`} className="ranking-row" key={district.slug}><b>#{String(index+1).padStart(2, '0')}</b><span>{district.name}</span><div><i style={{width: `${(district[measure] / (sorted[0]?.[measure] || 1)) * 100}%`}} /></div><strong>{formatter.format(district[measure])}</strong></Link>) : <div className="empty-copy">Import your Excel workbook to see rankings.</div>}</section>
  </>
}
