import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, Treemap, XAxis, YAxis } from 'recharts'
import { useNavigate } from 'react-router-dom'
import { getEducationMultiYearOverview } from '../api'
import DistrictCombobox from '../components/DistrictCombobox'
import '../education-dashboard.css'

const colors=['#6c3cf0','#9d5ce6','#f59e0b','#ec4899','#4e9ce6','#4ba879','#c18c4e']
const format=value=>value==null?'—':new Intl.NumberFormat('en-IN').format(value)
const tooltipStyle={borderRadius:12,border:'1px solid #eee2d6',boxShadow:'0 10px 24px #41206e1f'}
function TreemapCell({x,y,width,height,index,name,value}) { return <g><rect x={x} y={y} width={width} height={height} fill={colors[index%colors.length]} stroke="#fff" strokeWidth={2} rx={5}/>{width>70&&height>35&&<text x={x+9} y={y+19} fill="#fff" fontSize={11} fontWeight="700">{name}</text>}{width>70&&height>52&&<text x={x+9} y={y+35} fill="#fff" fontSize={10}>{format(value)}</text>}</g> }
const totalFor=(district,type)=>type==='All'?district.total_schools:district.school_distribution?.[type]

export default function SchoolInfrastructure() {
  const [data,setData]=useState(null),[error,setError]=useState(''),[year,setYear]=useState('All Years'),[districtSlug,setDistrictSlug]=useState(''),[type,setType]=useState('All'),[sortBy,setSortBy]=useState('total_schools')
  const navigate=useNavigate(); useEffect(()=>{getEducationMultiYearOverview().then(setData).catch(item=>setError(item.message))},[])
  const annual=data?.annual||[], selected=year==='All Years'?null:data?.by_year?.[year]
  const source=selected?.districts||annual.find(item=>item.availability.schools)?.districts||[]
  const categories=useMemo(()=>[...new Set((year==='All Years'?annual.flatMap(item=>item.districts):source).flatMap(district=>Object.keys(district.school_distribution||{})))],[annual,source,year])
  useEffect(()=>{if(type!=='All'&&!categories.includes(type))setType('All');if(sortBy!=='total_schools'&&!categories.includes(sortBy))setSortBy('total_schools')},[categories,type,sortBy])
  if(!data&&!error)return <div className="loading">Loading school infrastructure…</div>
  if(error)return <div className="notice">{error}</div>
  return <div className="school-infrastructure"><section className="infrastructure-heading"><div><p className="eyebrow">Education analytics · school infrastructure</p><h1>School infrastructure explorer</h1><p>District-wise school availability from the supplied reporting-year datasets.</p></div><div className="infrastructure-total"><span>Reported schools</span><strong>{format(selected?.total_schools ?? latestSchoolYear(annual)?.total_schools)}</strong><small>{year==='All Years'?'Latest available school report':`${source.length} reporting districts`}</small></div></section><section className="infra-filters"><DistrictCombobox districts={source} value={districtSlug} onChange={setDistrictSlug} label="Filter district"/><label>School type<select value={type} onChange={event=>setType(event.target.value)}><option>All</option>{categories.map(category=><option key={category}>{category}</option>)}</select></label><label>Rank table by<select value={sortBy} onChange={event=>setSortBy(event.target.value)}><option value="total_schools">Total schools</option>{categories.map(category=><option key={category} value={category}>{category} schools</option>)}</select></label><label>Year<select value={year} onChange={event=>setYear(event.target.value)}><option>All Years</option>{annual.map(item=><option key={item.year}>{item.year}</option>)}</select></label></section>{selected?<SelectedYear yearData={selected} categories={categories} districtSlug={districtSlug} type={type} sortBy={sortBy} navigate={navigate}/>:<AllYears annual={annual} categories={categories} districtSlug={districtSlug} type={type} sortBy={sortBy} navigate={navigate}/>}</div>
}
function SelectedYear({yearData,categories,districtSlug,type,sortBy,navigate}) { const districts=yearData.districts||[], visible=districtSlug?districts.filter(item=>item.slug===districtSlug):districts, totals=Object.fromEntries(categories.map(name=>[name,visible.reduce((sum,item)=>sum+(item.school_distribution?.[name]||0),0)])), selectedTotal=item=>totalFor(item,type), sorted=[...visible].sort((a,b)=>(totalFor(b,sortBy==='total_schools'?'All':sortBy)||0)-(totalFor(a,sortBy==='total_schools'?'All':sortBy)||0)), top=[...visible].sort((a,b)=>(selectedTotal(b)||0)-(selectedTotal(a)||0)).slice(0,10).reverse().map(item=>({name:item.name,value:selectedTotal(item)})), stackData=visible.slice(0,10).map(item=>({name:item.name,...item.school_distribution})); return <><section className="infrastructure-kpis">{categories.map((name,index)=><article key={name}><i style={{background:colors[index]}}/><span>{name} schools</span><strong>{format(totals[name])}</strong><small>{yearData.total_schools?((totals[name]/yearData.total_schools)*100).toFixed(1):0}% of reported schools</small></article>)}</section><section className="infra-main-charts"><SchoolDonut title="School category share" data={totals}/><Stacked title="Infrastructure mix by district" data={stackData} categories={categories} xKey="name"/><SchoolTree title="Statewide school treemap" data={totals}/></section><Ranking title="District rankings" detail={`Top 10 districts by ${type==='All'?'total schools':`${type.toLowerCase()} schools`}.`} data={top}/><SchoolTable districts={sorted} categories={categories} navigate={navigate}/></> }
function AllYears({annual,categories,districtSlug,type,sortBy,navigate}) { const schoolYears=annual.filter(item=>item.availability.schools), latest=schoolYears.at(-1), scope=item=>districtSlug?item.districts.filter(district=>district.slug===districtSlug):item.districts, totals=item=>{const rows=scope(item);return Object.fromEntries(categories.map(name=>{const reported=rows.some(district=>Object.hasOwn(district.school_distribution||{},name));return [name,reported?rows.reduce((sum,district)=>sum+(district.school_distribution?.[name]||0),0):null]}))}, series=schoolYears.map(item=>({year:item.year,...totals(item)})), latestTotals=totals(latest), latestDistricts=scope(latest), selectedTotal=district=>totalFor(district,type), rankingNames=[...latestDistricts].sort((a,b)=>(selectedTotal(b)||0)-(selectedTotal(a)||0)).slice(0,10).map(item=>item.slug), rankSeries=rankingNames.map(slug=>{const row={name:latest.districts.find(item=>item.slug===slug)?.name};schoolYears.forEach(item=>{const district=item.districts.find(entry=>entry.slug===slug);row[item.year]=district?totalFor(district,type):null});return row}), districtRows=new Map(); schoolYears.forEach(item=>scope(item).forEach(district=>{const row=districtRows.get(district.slug)||{slug:district.slug,name:district.name};row[item.year]=totalFor(district,type);districtRows.set(district.slug,row)}));const table=[...districtRows.values()].sort((a,b)=>(b[latest.year]||0)-(a[latest.year]||0)); return <><section className="infrastructure-kpis">{categories.map((name,index)=><article key={name}><i style={{background:colors[index]}}/><span>{name} schools</span><strong>{format(latestTotals[name])}</strong><small>{latest.year} latest available report</small></article>)}</section><section className="infra-main-charts"><Stacked title="School categories across reporting years" data={series} categories={categories}/><SchoolDonut title={`School category distribution · ${latest.year}`} data={latestTotals}/><SchoolTree title={`Statewide school treemap · ${latest.year}`} data={latestTotals}/></section><section className="infra-ranking-card"><div><h2>District ranking comparison</h2><p>Top latest-year districts, compared across all supplied school reporting years.</p></div><ResponsiveContainer width="100%" height={340}><BarChart data={rankSeries} margin={{left:4,right:8}}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey="name" tickFormatter={value=>value.split(' ')[0]} tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{fontSize:10}}/>{schoolYears.map((item,index)=><Bar key={item.year} dataKey={item.year} fill={colors[index%colors.length]} radius={[5,5,0,0]}/>)}</BarChart></ResponsiveContainer></section><SchoolTable districts={table} categories={[]} years={schoolYears.map(item=>item.year)} navigate={navigate} yearWise/></> }
function SchoolDonut({title,data}) { const items=Object.entries(data).map(([name,value])=>({name,value})).filter(item=>item.value);return <article className="education-chart-card"><h3>{title}</h3><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={items} dataKey="value" nameKey="name" innerRadius={65} outerRadius={100} paddingAngle={2}>{items.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></article> }
function Stacked({title,data,categories,xKey='year'}) { return <article className="education-chart-card"><h3>{title}</h3><ResponsiveContainer width="100%" height={290}><BarChart data={data} margin={{left:-18,right:3}}><CartesianGrid vertical={false} stroke="#eee6dc"/><XAxis dataKey={xKey} tickFormatter={value=>String(value).split(' ')[0]} tick={{fontSize:9}}/><YAxis tick={{fontSize:10}}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Legend wrapperStyle={{fontSize:9}}/>{categories.map((category,index)=><Bar key={category} dataKey={category} stackId="schools" fill={colors[index%colors.length]}/>)}</BarChart></ResponsiveContainer></article> }
function SchoolTree({title,data}) { const items=Object.entries(data).map(([name,value])=>({name,value})).filter(item=>item.value);return <article className="education-chart-card"><h3>{title}</h3><ResponsiveContainer width="100%" height={290}><Treemap data={items} dataKey="value" aspectRatio={4/3} content={<TreemapCell/>}><Tooltip contentStyle={tooltipStyle} formatter={format}/></Treemap></ResponsiveContainer></article> }
function Ranking({title,detail,data}) { return <section className="infra-ranking-card"><div><h2>{title}</h2><p>{detail}</p></div><ResponsiveContainer width="100%" height={330}><BarChart data={data} layout="vertical" margin={{left:10,right:20}}><CartesianGrid horizontal={false} stroke="#eee6dc"/><XAxis type="number" tick={{fontSize:10}}/><YAxis type="category" dataKey="name" width={115} tick={{fontSize:10}}/><Tooltip contentStyle={tooltipStyle} formatter={format}/><Bar dataKey="value" fill="#6c3cf0" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></section> }
function SchoolTable({districts,categories,years=[],yearWise=false,navigate}) { return <section className="infra-table-card"><div className="infra-table-title"><div><h2>District-wise school table</h2><p>Click any district to open its education profile.</p></div><span>{districts.length} districts shown</span></div><div className="infra-table-wrap"><table><thead><tr><th>District</th>{yearWise?years.map(year=><th key={year}>{year}</th>):<><th>Total schools</th>{categories.map(category=><th key={category}>{category}</th>)}</>}</tr></thead><tbody>{districts.map(district=><tr key={district.slug} onClick={()=>navigate(`/education/districts/${district.slug}`)}><td><b>{district.name}</b><small>View district analytics →</small></td>{yearWise?years.map(year=><td key={year}>{format(district[year])}</td>):<><td>{format(district.total_schools)}</td>{categories.map(category=><td key={category}>{format(district.school_distribution?.[category])}</td>)}</>}</tr>)}</tbody></table></div></section> }
const latestSchoolYear=annual=>[...annual].reverse().find(item=>item.availability.schools)
