# Generated by Django 6.0.7 on 2026-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('population_total', models.PositiveBigIntegerField(default=0)),
                ('population_male', models.PositiveBigIntegerField(default=0)),
                ('population_female', models.PositiveBigIntegerField(default=0)),
                ('area_sq_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('births', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('gram_panchayats', models.PositiveIntegerField(default=0)),
                ('municipalities', models.PositiveIntegerField(default=0)),
                ('municipal_corporations', models.PositiveIntegerField(default=0)),
                ('urban_population', models.PositiveBigIntegerField(default=0)),
                ('collector_name', models.CharField(blank=True, max_length=150)),
                ('state_contribution_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('source_year', models.PositiveSmallIntegerField(default=2025)),
                ('facts', models.TextField(blank=True, help_text='One interesting fact per line')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
