# Generated by Django 6.0.7 on 2026-07-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='births_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='births_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='corporation_births',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='corporation_deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='deaths_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='deaths_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='gram_panchayat_births',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='gram_panchayat_deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='municipality_births',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='municipality_deaths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
