# Generated by Django 6.0.7 on 2026-07-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_district_births_female_district_births_male_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_type', models.CharField(choices=[('gram_panchayat', 'Gram Panchayat'), ('municipality', 'Municipality'), ('corporation', 'Municipal Corporation')], max_length=20)),
                ('births', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('births_male', models.PositiveIntegerField(default=0)),
                ('births_female', models.PositiveIntegerField(default=0)),
                ('deaths_male', models.PositiveIntegerField(default=0)),
                ('deaths_female', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_bodies', to='demographics.district')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('district', 'body_type', 'name'), name='unique_local_body')],
            },
        ),
    ]
